import type {Metadata} from 'next';
import {Roboto} from 'next/font/google';
import './globals.css';
import Header from '@/components/shared/Header/Header';
import Footer from '@/components/shared/Footer/Footer';

const metalSans = Roboto({
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${metalSans.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
