import type {Metadata} from 'next';
import {Roboto} from 'next/font/google';
import './globals.css';
import Header from '@/components/shared/Header/Header';
import Footer from '@/components/shared/Footer/Footer';

import s from './Home.module.scss';

const metalSans = Roboto({
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'HeroMaker',
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${metalSans.className} antialiased`}>
        <div className={s.layout}>
          <Header />
          <main className={s.main_content}>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
